name: sync notionfolio

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: "src/app"
          destination-github-username: "mehdibha"
          destination-repository-name: "notionfolio"
          user-email: hello@mehdibha.co
          target-branch: main
          create-target-branch-if-needed: true
