name: LaTeX to PDF Conversion

on:
  push:
    branches:
      - main  # Replace with the default branch name of your repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install TinyTeX and Dependencies
      run: |
        # Install TinyTeX
        wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh -
        export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH
        sudo apt-get install -y libpoppler-cpp-dev  # Install a dependency

        # Install additional LaTeX packages if needed
        # tlmgr install package_name

    - name: Compile LaTeX to PDF
      run: |
        # Compile LaTeX to PDF
        pdflatex -interaction=nonstopmode your_latex_file.tex
        pdflatex -interaction=nonstopmode your_latex_file.tex  # Run twice for correct references

    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf
        path: your_latex_file.pdf
